compatibility_date = "2024-02-21"
node_compat = true
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cosmos_db_prod"
database_id = "19885b0b-8e77-4773-91c9-f55ca444e734"
